config/routes.rb
Rails.application.routes.draw do

  resources :blogs do
  collection do
      post :confirm
  end
  end

  root to: 'tops#index'

  resources :sessions, only: [:new, :create, :destroy]
  resources :users

  resources :favorites, only: [:create, :destroy]
mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  belongs_to :user

  validates :title,:content, presence: true
  validates :content, length:  { in: 1..140 }

  mount_uploader :image, ImageUploader
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  has_many :favorites, dependent: :destroy
  has_many :blogs,dependent: :destroy
  has_many :favorite_blogs, through: :favorites,source: :blog


  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  mount_uploader :icon, IconUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
    before_action :set_blog, only:[:show,:edit,:update,:destroy]
    before_action :logged_in_user, only: [:new,:index,:edit,:show,:destroy]

    def index
        @blogs = Blog.all
    end

    def new
      if params[:back]
          @blog = Blog.new(blog_params)
      else
          @blog = Blog.new
      end

    end

    def create
        @blog = Blog.new(blog_params)
        @blog.user_id = current_user.id #現在ログインしているuserのidをblog.user_idに代入し、blogのuser_idカラムに挿入
        #user_idはすでに、テーブルが関連づけられているだけでは、使用できない。アソシエーションをかけ、t.referencesを使用して、外部キーの
        #カラムをblogsに作成する。また、その際,外部キーを使用する際、blogsは belongs_to :user　になる

        if @blog.save
          # メール送信機能
          #ContactMailer.contact_mail(@blog).deliver
          redirect_to blogs_path, notice: 'ブログが作成されました'
        else
          render 'new'
        end
    end

    def show
      @favorite = current_user.favorites.find_by(blog_id: @blog.id)
    end

    def edit
    end

    def update
      if @blog.update(blog_params)
        redirect_to blogs_path, notice: '編集しました'
      else
        render 'edit'
      end
    end

    def destroy
        @blog.destroy
        redirect_to blogs_path, notice: 'ブログを削除しました'
    end

    def confirm
      @blog = Blog.new(blog_params)
      #ここにも記入
      @blog.user_id = current_user.id
      render :new if @blog.invalid?  # render 'new'でもいいはず
    end


    private
    def blog_params
        params.require(:blog).permit(:title, :content, :image, :image_cache)
    end
    def set_blog
       @blog = Blog.find(params[:id])
    end
    def logged_in_user
      unless current_user #ログイン中のuserでない場合は、ログイン画面へリダイレクト
        render new_session_path
      end
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(blog_id: params[:blog_id])
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    #送信されたメールアドレスをparams[:session][:email]で取得し、そのemailをfind_byメソッドでデータベースからユーザを取り出しています。

    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      #ログイン成功した場合
      session[:user_id] = user.id #これはuserのidを付与しているとみられる。ユーザーのブラウザ内のcookiesに暗号化されたユーザーIDが自動で生成されます。
      redirect_to user_path(current_user.id)
    else
      #ログイン失敗した場合
      flash.now[:danger] = 'ログインに失敗しました'
      render 'new'
    end

  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      #signinしたら,login状態にさせる
      #session[:user_id] = @user.id
      redirect_to new_blog_path
    #保存した場合
    # redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end

  def show
    @user = current_user
    @favorite_blogs = @user.favorite_blogs
  end

  private

  def user_params
   params.require(:user).permit(:name,:email,:password,:password_confirmation, :icon, :icon_cache)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/blogs_helper.rb
module BlogsHelper
    def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
    end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    #セッションidを保持している。@current_userが真の場合はそのままにし、偽の場合は右辺の値 User.find_by(id: session[:user_id]) を代入するというものです。
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<div class = "container">
<%= form_with(model: @blog, local: true, url: choose_new_or_edit) do |form| %>
  <% if @blog.errors.any? %>

 <div class ="field_with_errors">
      <p><%= @blog.errors.count %>件のエラーがあります。</p>

      <% @blog.errors.full_messages.each do |msg| %>
      <p><%= msg %><p>
      <% end %>

    </div>
  <% end %>

  <div class="blog_title">
      <%= form.label :title %>
      <%= form.text_field :title %>
  </div>
  <div class="blog_title">
      <%= form.label :content %>
      <%= form.text_area :content ,size: "45x10" %>
  </div>

  <div class = "blog_title">
    <%= form.label :image %>
    <!-- 確認画面から新規作成画面に戻った時に、 -->
    <!-- アップロードした画像を表示させるための記述 -->
    <%= image_tag(@blog.image.url) if @blog.image.url %>
    <%= form.file_field :image, id: :blog_image %>
  </div>

  <%= form.submit "登録する", class: 'btn btn-info' %>
  <%= link_to "ブログ一覧にもどる", blogs_path, class: 'btn btn-info' %>
  <% end %>
</div>

</div>

app/views/blogs/confirm.html.erb
<div class ="container">
    <h3>以下の内容で、送信する。</h3>

  <%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
    <%= form.hidden_field :title %>
    <%= form.hidden_field :content %>
    <%= form.hidden_field :image_cache %>

    <div class="wrapper">
      <p>タイトル:<%= @blog.title %></p>
      <p>本文:<%= @blog.content %></p>
      <!-- 確認画面でアップロードした画像を表示させるための記述 -->
      <%= image_tag(@blog.image) %>
    </div>
    <%= form.submit  "登録する" ,class: 'btn btn-info'%>
  <% end %>


  <%= form_with(model: @blog, url: new_blog_path, local: true, method: 'get') do |form| %>
    <%= form.hidden_field :title %>
    <%= form.hidden_field :content %>
    <%= form.hidden_field :image_cache %>
    <%= form.submit "もどる", name: 'back', class: 'btn btn-info' %>
  <% end %>
</div>

app/views/blogs/edit.html.erb
<div class ="container">
  <div class="wrappaer">
    <h2>ブログを編集する</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/blogs/index.html.erb
<div class="container">

   <div class="contents">
     <h1>DailyBlog</hi>
       <p><%= notice %></p>

   <% @blogs.each do |blog| %>
    <ul class = 'row'>
        <li class = "col-sm-6 col-md-6 test" >タイトル:<%= blog.title %></li>
        <li class = "col-sm-6 col-md-6 test">内容:<%= blog.content %></li>
    </ul>
        <%= link_to 'ブログを確認する', blog_path(blog.id), class: 'btn btn-info' %>
    <% if blog.user_id == current_user.id %>
        <%= link_to 'ブログを編集する', edit_blog_path(blog.id), class: 'btn btn-info' %>
        <%= link_to 'ブログを削除する', blog_path(blog.id), method: :delete ,data: { confirm: '本当に削除してよろしいですか'}, class: 'btn btn-info' %>
    <% end %>
    <% end %>
</div>
</div>

app/views/blogs/new.html.erb
<div class ="container">
  <div class="contents">
    <h1>ブログを作成する</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/blogs/show.html.erb
<div class ="container">
  <div class="contents">
    <h1>ブログ詳細画面</h1>
    <% unless @blog.user == current_user %>
      <% if @favorite.present? %>
        <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
      <% else %>
        <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-info' %>
      <% end %>
    <% end %>

    <p>タイトル: <%= @blog.title %></p>
    <p>内容: <%= @blog.content %></p>
    <p id="notice"><%= notice %></p>
    <p><strong>Image:</strong>
    <%= image_tag @blog.image %></p>

    <%= link_to '戻る', :back ,class: 'btn btn-info' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogapp</title>
    <%= csrf_meta_tags %>

<meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<body>
<header>
  <ul>
    <li><%=link_to "ホーム", root_path %></li>
    <li><%=link_to "一覧",blogs_path %></li>
    <li><%=link_to "つぶやく",new_blog_path %></li>
    
    <% if logged_in? %>
      <li><%=link_to "プロフィール", user_path(current_user.id) %></li>
      <li class ="log"><%= link_to "Logout", session_path(current_user.id), method: :delete %></li>
    <% else %>
      <li class ="log"><%= link_to "Sign up", new_user_path %></li>
      <li class ="log"><%= link_to "Login", new_session_path %></li>
    <% end %>
  </ul>

</header>
   <div class ="main">
     <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <%= yield %>
   </div>

<footer>
  <p>HIROTOSHI KAWABUCHI</p>
  <p>© 2015-2016 Copyright DIVE INTO CODE.</p>
</footer>
</body>
</html>

app/views/tops/index.html.erb
<div class = "top">

<h1 class = 'name'><span class="label label-success">MY BLOG!</span></h1>
<article class='explain'>
    <ul>
        <li>日常を書き留めます</li>
        <li>bootstrapを使ってページ作成！</li>
    </ul>
</article>

</div>

app/views/users/new.html.erb
<div class = "container">
<h1>SignUp!</h1>

  <% if @user.errors.any? %>
<div id = "error_explanation">
  <h2><%= pluralize(@user.errors.count, "error" ) %> prohibited this @user from being saved:</h2>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
</div>
<% end %>
<div class = "sign">
<%= form_with( model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control", placeholder: "User Name" %>

  <%= f.label :email %>
  <%= f.email_field :email,class: "form-control", placeholder: "Email" %>

  <%= f.label :password %>
  <%= f.password_field :password, class: "form-control", placeholder: "Password" %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Password Comfirmation" %>

  <%= f.label :登録写真 %>
  <%= f.file_field :icon, id: :user_icon %>

  <%= f.submit "SignUp", class: 'btn btn-info' %>
<% end %>

<p class="mt-5 mb-3 text-muted">© 2017-2018</p>
</div>

app/views/users/show.html.erb
<div class = "container">
  <h1><%= @user.try(:name) %>のアカウントページ</h1>
  <P>メールアドレス:<%= @user.try(:email) %></p>
  <%= image_tag @user.icon %></p>
    <br>
    <h2>お気に入り</h2>
    <% @favorite_blogs.each do |favorite_blog| %>
    <p><%=  favorite_blog.user.name %></p>
      <ul class = 'row'>
        <li class = "col-sm-6 col-md-6">タイトル:<%= favorite_blog.title %></li>
        <li class = "col-sm-6 col-md-6">内容:<%= favorite_blog.content %></li>
      </ul>
    <% end %>
</div>